{% set name = "jobtastic" %}
{% set version = "2.1.1" %}
{% set hash_type = "sha256" %}
{% set hash_val = "74ec5789d889b10909066da99a225d97b667143f0e7060fbadbc69117a2a4a8e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/PolicyStat/{{ name }}/archive/v{{ version }}.tar.gz
  {{hash_type}}: {{ hash_val }}

build:
  skip: true  # [not py27]
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
 
  run:
    - python
    - psutil >=3.0,<4
    - celery >=3.1,<5

test:
  imports:
    - jobtastic

  requires:
    - django >=1.4,<2
    - django-celery >=3.0,<4
    - django-nose
    - mock
    - unittest2  # [py26]

about:
  home: http://policystat.github.com/jobtastic
  license: MIT 
  license_file: LICENSE
  summary: 'Make your user-facing Celery jobs totally awesomer'

  description: |
    Jobtastic makes your user-responsive long-running Celery jobs totally awesomer. 
    Celery is the ubiquitous python job queueing tool and jobtastic is a python 
    library that adds useful features to your Celery tasks. Specifically, these are
    features you probably want if the results of your jobs are expensive or if your 
    users need to wait while they compute their results.
  dev_url: http://policystat.github.com/jobtastic

extra:
  recipe-maintainers:
    - sodre
