travis:
  secure:
    BINSTAR_TOKEN: Z8IjhQnFQtaatcIjDbypzLouTEKeSRfR0gZb2GY5Kw565NPMFlLwxe7W55cLf9a45Dq54lHeB19gDpBtvyO53D6zUuzOSJZlQ/v9e8n0mIDvrqWXM62rYsRgvqeQ9ikJCitTPPqI8NOL53kxQ7aTE9gL8lFI0LGdbDTIQO5gpPWGWI8zOZagXHfSBMIg+TD/j2uYUaDloAZHnlFvs9EB4k9QKtYv6aPYn90uKywtUgwY4b5AXO43nWrf7puZV0PEm7zO+z2OmIghVGO4noVsSdyw098sMbUTqHj1kwhptVmIksXyYw/+jXq/DSNE/tvZ0MVdfK/N0DzniQkpTxSEmI5QNgZlxVP6Fvo3XzIfS6aRl/ICtGNAa84ch8WoiKN5GC3HAcx8EixjDcvL0fK0iwPaDMd/d4mNobzRKQZpTPUoTZBNxrimwOs6xA4xVR3/8Ng5mIYyT2vhjaRZBzz8ZwkWc6Tid83RBbMy83JZ9XAEEnLa37nr0OPhtuUUrMeGJXW2Zi18LY/ynDhTt4gOOJZjobKbTZnp8MICzXf4UfZPPlhfBZdydP5/7KoHHs/TF0hC6+Z2sfRHRRxVe8AHxhhvFENAO+QjjlksMZoW3i6IegPuqF5K79IyMAMm+Ezxp7CCKGUtXhSNfh6529yUPrLmo15aq5st4BNGUzJ79cE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
