travis:
  secure:
    BINSTAR_TOKEN: fG4zORrBnmMSFvTGj+3GfHDKfvF4QgJ4YWEmSF/lWAK10jt7wOzr/tAENPmfyyVIkZA8L9hx1G5Qh2lEAlQq3Tv1lRCKX9MRmAnA3g+OOvp+ZwXdvTh9gnYEnpFNbK5+BahF6koU+Hif9C5t0ojtaPSFNHivxb5z4iOEKyfn6vZgrtgECAOkuNKRNu+pL1orrqtl2WrP9gmkTgu5WTd7jgRJvWyoiIgaNB6WqbsTQRwtma0SghF/INqqA8W3lxuiyUY8z/qddfIW2EWabqNI26UYR8exLAMz/0kOlMaDNQCpuWV80WN3VA4NOlMwUcKJRrrSIrFv83WRWInQJFyf/8pd3Ut0ayEUtDse2bw7Eo9kQV2/xaaG2HP2furFVWzVXcUnxAVEOnM4tO5rUXGPZetXcIcpkswl9f5gI0f7sKlRq8Ekr6AIccsXnt/lWBi0hw7ORi2z/vObZ4sF07FI8WhrvlDN4BXfXqXaLzaXRBYi76lvSREVvvAH5PYDuRpDH65aIff9LC+hncpFWTzjhuE5uQrpjFgDbfg0PRJ7lVh25IZQoPYUSDxV0XEkzQD90zw4U/j0UR9wqtR57kqbuu1JkP8nRvcRajdrhQHKeNnpponvfTjoEprwnd8WBoQiWT4YnzZ++do/6uia2V9QOCVt0g9anOhW8e7m6LtMMoM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
