travis:
  secure:
    BINSTAR_TOKEN: xCZCVsirgGnsGm09FRyA6tqOnu7+4S6W7Y2incHHtHU4joVAAJPBum44QXTdt2wnMiHbxjtyXYPW+ym1Nh6FCGUlbAX5AwccoBAdmTScDUplqe9LfCW3X6fo8Py6gDVACrxZyeqv6q4uty4YdLF6QSoFd3DP28PtwJM605DklMYYd/az/P4CXCmsgKYDtsQzNhWJyJop2eb+N5S5oUzxTvdckyBeIYc4AaB+wzsGmddfWlyONnpaOu5I50pozBe8ZKdOrAYMH6SZjJOpLN9smkI7TrJotDlPwVmA7PrPsnGnbvcJgOmdMlrcUk65bzESULcmEq5l0COd4nGxc8ELgMvzg+Z2d8IpBKxe/jzKGHt6s++VrvHcwi8lfJAyWge7S4CmBq7MTldEE3nssE86k+CObYOYRKLzCmtyzNBJIA1VB7Obi0FqF7Fw67nUZoTdfqmAOPcQolTdLUi4+5/YIaa1fqwKOfNdlreHCORLcNZExKbAQSwHUl2qM+xMbkyA4jr+cAGQoS6jCOwUWgLfx4tXYGvV/RmDfiJbi6+ipe0IsKLv4CQqKvHoBp/GeEWXkDi+yz77WHLpFaKRz4agTTARU1q1uWiFV8/xvy++J9P/yR6oWwi7ZmdqXkteG0zl6z3OCb5ishiTJ50nhWYFXDU40ARlyg58/bWSbKg2xVk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
